<a href="https://colab.research.google.com/github/ash-iitbhu/Deep_learning_handson/blob/main/tensors_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("CUDA is available")
    print("Number of GPUs available:", torch.cuda.device_count())
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available using CPU")

CUDA is available
Number of GPUs available: 1
GPU name: Tesla T4


In [4]:
device = torch.device('cuda')
device

device(type='cuda')

In [5]:
a = torch.tensor([[1,2,3],[4,5,6]],device=device)

In [6]:
a

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [7]:
b = torch.tensor([[1,2,3],[4,5,6]])

In [10]:
c = b.to(device)

In [13]:
c

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [16]:
import time
size =10000

a_cpu = torch.randn(size,size)
b_cpu = torch.rand(size,size)

start_time = time.time()
mul_cpu = torch.matmul(a_cpu,b_cpu)
cpu_time = time.time() -start_time


start_time =time.time()
a_gpu = a_cpu.to(device)
b_gpu = b_cpu.to(device)
mul_gpu = torch.matmul(a_gpu,b_gpu)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"cpu time: {cpu_time}")
print(f"gpu time: {gpu_time}")




cpu time: 15.029078483581543
gpu time: 0.7386391162872314


# **Create Tensors**



In [4]:
a = torch.empty(2,3)

In [5]:
a

tensor([[0.0000e+00, 0.0000e+00, 1.4153e-43],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
type(a)

torch.Tensor

In [13]:
b = torch.zeros(3,4)
c = torch.ones(2)


In [10]:
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
c

tensor([1., 1.])

In [18]:
torch.manual_seed(100)
d = torch.rand(1,2)
print(d)

tensor([[0.1117, 0.8158]])


In [19]:
list1 = [[1,2,3],[4,5,6]]
tensor1 = torch.tensor(list1)
print(tensor1)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [21]:
print(f"using arange :{torch.arange(1,10,2)}")
print(f"using eye: {torch.eye(3)}")
print(f"using linspace: {torch.linspace(1,10,5)}")
print(f"using full: {torch.full((2,3),5)}")

using arange :tensor([1, 3, 5, 7, 9])
using eye: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using linspace: tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
using full: tensor([[5, 5, 5],
        [5, 5, 5]])


# **Tensor Shape**

In [22]:
b.shape

torch.Size([3, 4])

In [25]:
b.shape[1]

4

In [26]:
torch.empty_like(b)

tensor([[ 0.0000e+00,  9.3455e+05,  4.8593e-38,  1.6763e-37],
        [-2.1990e+12,  4.3061e-41,  1.5077e-38,  0.0000e+00],
        [ 2.1529e-38,  1.9639e+19,  1.1351e-43,  0.0000e+00]])

In [29]:
torch.zeros(b.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
torch.rand_like(b)

tensor([[0.4183, 0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784, 0.8238],
        [0.5557, 0.9770, 0.4440, 0.9478]])

# **Tensor data types**

In [31]:
b.dtype

torch.float32

In [32]:
a = torch.tensor([[1,2,3],[4,5,6]])

In [34]:
a.dtype

torch.int64

In [36]:
b = torch.tensor([[1,2,3],[4,5,6]],dtype = torch.float16)

In [37]:
b.dtype

torch.float16

In [38]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [42]:
a =a.to(torch.float32)

In [43]:
a.dtype

torch.float32

# **Mathematical operations**

In [45]:
a = torch.rand(2,3)
a

tensor([[0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064]])

In [46]:
print(a+2)
print(a*2)
print(a/2)
print((a*100)//3)
print((a*100)%3)
print(a**2)

tensor([[2.7909, 2.4235, 2.0169],
        [2.2209, 2.9535, 2.7064]])
tensor([[1.5818, 0.8470, 0.0338],
        [0.4418, 1.9071, 1.4128]])
tensor([[0.3954, 0.2117, 0.0084],
        [0.1104, 0.4768, 0.3532]])
tensor([[26., 14.,  0.],
        [ 7., 31., 23.]])
tensor([[1.0886, 0.3487, 1.6899],
        [1.0895, 2.3536, 1.6403]])
tensor([[6.2550e-01, 1.7934e-01, 2.8558e-04],
        [4.8794e-02, 9.0923e-01, 4.9901e-01]])


In [52]:
torch.abs(torch.neg(a))

tensor([[0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064]])

In [53]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [54]:
torch.clamp(b,min=1,max=3)

tensor([[1., 2., 3.],
        [3., 3., 3.]], dtype=torch.float16)

# **Reduction function**

In [56]:
a = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [57]:
print(torch.sum(a))
print(torch.sum(a,dim=0))
print(torch.sum(a,dim=1))

tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])


In [58]:
#min, max, median, mean, std, var, argmax, argmin

In [59]:
print(torch.argmax(a))
print(torch.argmin(a))

tensor(5)
tensor(0)


In [60]:
print(torch.argmax(a,dim=0))
print(torch.argmin(a,dim=1))

tensor([1, 1, 1])
tensor([0, 0])


# **Matrix Operations**

In [65]:
a = torch.randint(size=(2,3),low=0,high=10)
b = torch.randint(size=(3,2),low=0,high=10)
print(a)
print(b)

tensor([[9, 7, 5],
        [9, 8, 9]])
tensor([[7, 9],
        [2, 6],
        [7, 7]])


In [66]:
torch.matmul(a,b)

tensor([[112, 158],
        [142, 192]])

In [71]:
a = torch.tensor([1,2,3])
torch.dot(a,a)

tensor(14)

In [77]:
torch.transpose(b,0,1)

tensor([[7, 2, 7],
        [9, 6, 7]])

# **other operations**

In [95]:
a = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)

In [96]:
a.exp()

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [97]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [90]:
torch.exp(a)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [91]:
torch.sigmoid(a)

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 0.9975]])

In [92]:
torch.softmax(a,dim=0)

tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]])

In [93]:
torch.softmax(a,dim=1)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])

In [94]:
torch.relu(a)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [98]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# **Inplace Operations**

In [100]:
a.exp()

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [101]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [102]:
a.exp_()

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [103]:
a

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

# **Copying**

In [104]:
a

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [105]:
b =a

In [106]:
b

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [107]:
a[0][0] =0
a

tensor([[  0.0000,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [108]:
b

tensor([[  0.0000,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [109]:
b[0][0]=1
b

tensor([[  1.0000,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [110]:
a

tensor([[  1.0000,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [112]:
## because a and b both point to same locaiton in the memory
id(a),id(b)

(131983569854128, 131983569854128)

In [113]:
a

tensor([[  1.0000,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [114]:
b =a.clone()
b

tensor([[  1.0000,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [116]:
a[0][0] = 0
a

tensor([[  0.0000,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [117]:
b

tensor([[  1.0000,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [118]:
b[0][0] =-1
b

tensor([[ -1.0000,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [119]:
a

tensor([[  0.0000,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [120]:
id(a),id(b)

(131983569854128, 131983569053616)

# **Reshape**

In [18]:
 a = torch.tensor([[1,2,3],[4,5,6]])
 a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
a.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [22]:
a.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [24]:
a.reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [23]:
a.flatten()

tensor([1, 2, 3, 4, 5, 6])

In [25]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
a.unsqueeze(0) ### can be useful when creating batch, adding a new dimension at specific postition

tensor([[[1, 2, 3],
         [4, 5, 6]]])

# **numpy and pytorch**

In [31]:
import numpy as np

In [33]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
b = a.numpy()

In [35]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
type(b)

numpy.ndarray

In [37]:
d = torch.from_numpy(b)

In [39]:
print(type(d))
d

<class 'torch.Tensor'>


tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
d.dtype

torch.int64